# Generated by Django 3.1 on 2020-09-05 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0002_auto_20200905_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 20, 14, 7, 591608)),
        ),
    ]
