# Generated by Django 3.1 on 2020-09-06 18:06

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0002_auto_20200906_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 15, 6, 6, 497198)),
        ),
    ]
