# Generated by Django 3.1 on 2020-09-06 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0003_auto_20200905_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 23, 58, 40, 851553)),
        ),
    ]
