# Generated by Django 3.1 on 2020-09-06 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0004_auto_20200905_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 0, 1, 18, 745586)),
        ),
    ]
