# Generated by Django 3.1 on 2020-09-06 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0004_auto_20200906_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 19, 4, 50, 609261)),
        ),
    ]
