# Generated by Django 3.1 on 2020-09-06 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0003_auto_20200906_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 18, 55, 32, 888336)),
        ),
    ]
