# Generated by Django 3.1 on 2020-09-06 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0005_auto_20200906_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 19, 5, 57, 471453)),
        ),
    ]
