# Generated by Django 3.1 on 2020-09-07 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0010_auto_20200907_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 8, 27, 6, 384416)),
        ),
    ]
