# Generated by Django 3.1 on 2020-09-07 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0011_auto_20200907_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 14, 49, 23, 855008)),
        ),
    ]
