# Generated by Django 3.1 on 2020-09-07 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0012_auto_20200907_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 18, 2, 48, 290591)),
        ),
    ]
