# Generated by Django 3.1 on 2020-09-07 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0013_auto_20200907_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrito',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
