# Generated by Django 3.1 on 2020-09-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0014_auto_20200907_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
