# Generated by Django 3.1 on 2020-09-25 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escritos', '0015_auto_20200907_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrito',
            name='likes',
            field=models.ManyToManyField(related_name='post_escritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
