# Generated by Django 3.1 on 2020-09-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0018_auto_20200925_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
