# Generated by Django 3.1 on 2020-10-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0023_auto_20201008_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='vista',
            field=models.BooleanField(default=False),
        ),
    ]
