# Generated by Django 3.1 on 2020-10-13 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escritos', '0025_auto_20201012_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrito',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_escritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
