# Generated by Django 3.1 on 2020-09-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritos', '0022_comment_denuncias'),
        ('usuario', '0002_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='escritos_leidos',
            field=models.ManyToManyField(blank=True, related_name='escritos_leidos', to='escritos.Escrito'),
        ),
    ]
