# Generated by Django 3.1 on 2020-09-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.review'),
        ),
    ]
