# Generated by Django 3.1 on 2020-09-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20200927_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
