# Generated by Django 3.1 on 2020-09-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20200919_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
