# Generated by Django 3.1 on 2020-09-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20200920_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='desc',
            new_name='body',
        ),
    ]
