# Generated by Django 3.1 on 2020-10-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_denuncia_r_motivodenuncia_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia_r',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='denuncia_r',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='denuncia_r',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Comment_r',
        ),
        migrations.DeleteModel(
            name='Denuncia_r',
        ),
        migrations.DeleteModel(
            name='MotivoDenuncia_r',
        ),
    ]
