# Generated by Django 3.1 on 2020-10-25 18:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_auto_20201012_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True),
        ),
    ]
