# Generated by Django 3.1 on 2020-09-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_auto_20200920_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
